#Band Name Generator :)
print("Welcome to the Band Name Generator.")
city=input("What's the name of the city you grew up in?")
print(city)
name=input("What's your pet's name?")
print(name)
print("your band name could be " , city + " " +name)
